package explain

import (
	"fmt"
	"strings"

	"github.com/charmbracelet/lipgloss"
	"github.com/viniciussouzao/tidymymac/internal/tui/styles"
)

// FormatProfileResult renders an explain profile result as styled text.
func FormatProfileResult(result ProfileResult) string {
	var b strings.Builder

	b.WriteString(styles.Title.Render(result.Name.DisplayName()))
	b.WriteString("\n")
	if result.Summary != "" {
		b.WriteString(styles.Subtitle.Render(result.Summary))
		b.WriteString("\n")
	}
	b.WriteString("\n")

	b.WriteString("Explained by TidyMyMac: ")
	b.WriteString(styles.SizeStyled(result.TotalSize, result.TotalSizeHuman))
	b.WriteString("\n")
	if result.CoverageNote != "" {
		b.WriteString(styles.Dim.Render(result.CoverageNote))
		b.WriteString("\n")
	}
	b.WriteString("\n")

	for i, contributor := range result.Contributors {
		b.WriteString(renderContributorHeader(contributor))
		b.WriteString("\n")

		if contributor.HasError {
			b.WriteString(styles.Error.Render("Could not analyze this contributor: "))
			b.WriteString(styles.Error.Render(contributor.ErrorMessage))
			b.WriteString("\n")
			if i < len(result.Contributors)-1 {
				b.WriteString("\n")
			}
			continue
		}

		if contributor.TotalSize == 0 {
			b.WriteString(styles.Dim.Render("Nothing significant found."))
			b.WriteString("\n")
		} else if contributor.Context.WhatIsThis != "" {
			b.WriteString(contributor.Context.WhatIsThis)
			b.WriteString("\n")
		}

		if contributor.Context.WhatGenerates != "" {
			b.WriteString("Generated by: ")
			b.WriteString(contributor.Context.WhatGenerates)
			b.WriteString("\n")
		}
		if contributor.Context.WhyItAppears != "" {
			b.WriteString("Why it appears here: ")
			b.WriteString(contributor.Context.WhyItAppears)
			b.WriteString("\n")
		}
		if contributor.Context.Recommendation != "" {
			b.WriteString("Recommendation: ")
			b.WriteString(contributor.Context.Recommendation)
			b.WriteString("\n")
		}
		if contributor.Context.RelatedCommand != "" {
			b.WriteString("Related command: ")
			b.WriteString(contributor.Context.RelatedCommand)
			b.WriteString("\n")
		}

		if i < len(result.Contributors)-1 {
			b.WriteString("\n")
		}
	}

	return strings.TrimRight(b.String(), "\n")
}

func renderContributorHeader(contributor ContributorResult) string {
	var b strings.Builder

	b.WriteString(styles.CategoryHeader.Render(contributor.Name.DisplayName()))
	b.WriteString("  ")
	b.WriteString(styles.SizeStyled(contributor.TotalSize, contributor.TotalSizeHuman))
	b.WriteString("  ")
	b.WriteString(renderSafetyBadge(contributor.Context.SafetyLevel))

	return b.String()
}

func renderSafetyBadge(level SafetyLevel) string {
	switch level {
	case SafetyLevelSafe:
		return lipgloss.NewStyle().
			Bold(true).
			Foreground(lipgloss.Color("#0B1F13")).
			Background(lipgloss.Color("#10B981")).
			Padding(0, 1).
			Render("SAFE")
	case SafetyLevelCaution:
		return lipgloss.NewStyle().
			Bold(true).
			Foreground(lipgloss.Color("#201A00")).
			Background(lipgloss.Color("#F59E0B")).
			Padding(0, 1).
			Render("CAUTION")
	case SafetyLevelDoNotTouch:
		return lipgloss.NewStyle().
			Bold(true).
			Foreground(lipgloss.Color("#FFFFFF")).
			Background(lipgloss.Color("#EF4444")).
			Padding(0, 1).
			Render("DO NOT TOUCH")
	default:
		return styles.Dim.Render(fmt.Sprintf("[%s]", level))
	}
}
