package scriptgen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/viniciussouzao/tidymymac/internal/cleaner"
	"github.com/viniciussouzao/tidymymac/pkg/utils"
)

func Generate(results map[cleaner.Category]*cleaner.ScanResult, registry *cleaner.Registry) (string, error) {
	timestamp := time.Now().Format("20060102-150405")
	filename := fmt.Sprintf("tidymymac-cleanup-script-%s.sh", timestamp)

	cwd, err := os.Getwd()
	if err != nil {
		cwd = "."
	}

	outputPath := filepath.Join(cwd, filename)

	var b strings.Builder

	b.WriteString("#!/bin/bash\n")
	b.WriteString("# This script was generated by tidymymac to clean up files based on the scan results.\n")
	b.WriteString("# Please review the commands before running the script.\n\n")
	b.WriteString(strings.Repeat("#", 50))
	b.WriteString("\n")
	b.WriteString("# TidyMyMac Cleanup Script\n")
	b.WriteString(fmt.Sprintf("# Generated on: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	b.WriteString(strings.Repeat("#", 50))
	b.WriteString("#\n")
	b.WriteString("# Usage:\n")
	b.WriteString(fmt.Sprintf("#   chmod +x %s\n", filename))
	b.WriteString(fmt.Sprintf("#   ./%s\n", filename))
	b.WriteString("#\n")
	b.WriteString("# Some paths may require sudo. The script will warn you.\n")
	b.WriteString("#\n\n")

	// Set strict mode for better error handling.
	b.WriteString("set -euo pipefail\n\n")

	// Colors for output.
	b.WriteString("RED='\\033[0;31m'\n")
	b.WriteString("GREEN='\\033[0;32m'\n")
	b.WriteString("YELLOW='\\033[1;33m'\n")
	b.WriteString("NC='\\033[0m' # No Color\n\n")

	// Counters.
	b.WriteString("DELETED=0\n")
	b.WriteString("SKIPPED=0\n")
	b.WriteString("ERRORS=0\n\n")

	// Helper function.
	b.WriteString("safe_rm() {\n")
	b.WriteString("  local file=\"$1\"\n")
	b.WriteString("  if [ -f \"$file\" ]; then\n")
	b.WriteString("    if rm \"$file\" 2>/dev/null; then\n")
	b.WriteString("      DELETED=$((DELETED + 1))\n")
	b.WriteString("    else\n")
	b.WriteString("      echo -e \"${YELLOW}[SKIP]${NC} Permission denied: $file\"\n")
	b.WriteString("      SKIPPED=$((SKIPPED + 1))\n")
	b.WriteString("    fi\n")
	b.WriteString("  fi\n")
	b.WriteString("}\n\n")

	// Remove directory or any target recursively (used for Trash directories).
	b.WriteString("safe_rm_rf() {\n")
	b.WriteString("  local target=\"$1\"\n")
	b.WriteString("  if [ -e \"$target\" ]; then\n")
	b.WriteString("    if rm -rf \"$target\" 2>/dev/null; then\n")
	b.WriteString("      DELETED=$((DELETED + 1))\n")
	b.WriteString("    else\n")
	b.WriteString("      echo -e \"${YELLOW}[SKIP]${NC} Permission denied: $target\"\n")
	b.WriteString("      SKIPPED=$((SKIPPED + 1))\n")
	b.WriteString("    fi\n")
	b.WriteString("  fi\n")
	b.WriteString("}\n\n")

	// Confirmation prompt.
	b.WriteString("echo -e \"${YELLOW}TidyMyMac Cleanup Script${NC}\"\n")
	b.WriteString(fmt.Sprintf("echo \"This will delete %d files (%s)\"\n", totalFiles(results), utils.FormatBytes(totalBytes(results))))
	b.WriteString("echo \"\"\n")
	b.WriteString("read -p \"Are you sure? (y/N) \" confirm\n")
	b.WriteString("if [[ \"$confirm\" != \"y\" && \"$confirm\" != \"Y\" ]]; then\n")
	b.WriteString("  echo \"Aborted.\"\n")
	b.WriteString("  exit 0\n")
	b.WriteString("fi\n")
	b.WriteString("echo \"\"\n\n")

	// Generate rm commands per category.
	needsSudo := false
	for _, c := range registry.All() {
		result, ok := results[c.Category()]
		if !ok || len(result.Entries) == 0 {
			continue
		}

		b.WriteString(fmt.Sprintf("# === %s (%s, %d files) ===\n",
			c.Name(),
			utils.FormatBytes(result.TotalSize),
			result.TotalFiles,
		))
		b.WriteString(fmt.Sprintf("echo -e \"${GREEN}[%s]${NC} Cleaning %d files (%s)...\"\n",
			c.Name(), result.TotalFiles, utils.FormatBytes(result.TotalSize)))

		if c.RequiresSudo() {
			needsSudo = true
			b.WriteString("# NOTE: Some of these paths may require sudo\n")
		}

		// For command-based cleaners (homebrew, docker), emit their CLI commands.
		switch c.Category() {
		case cleaner.CategoryHomebrew:
			b.WriteString("if command -v brew &>/dev/null; then\n")
			b.WriteString("  echo \"Running brew cleanup...\"\n")
			b.WriteString("  brew cleanup\n")
			b.WriteString("else\n")
			b.WriteString("  echo -e \"${YELLOW}[SKIP]${NC} Homebrew not installed\"\n")
			b.WriteString("fi\n\n")
			continue

		case cleaner.CategoryDocker:
			b.WriteString("if command -v docker &>/dev/null && docker info &>/dev/null 2>&1; then\n")
			// Parse docker:// paths and emit specific rm/rmi/volume rm commands.
			for _, entry := range result.Entries {
				resourcePath := strings.TrimPrefix(entry.Path, "docker://")
				segments := strings.SplitN(resourcePath, "/", 3) // type/id/name
				if len(segments) < 2 {
					continue
				}
				resourceType := segments[0]
				resourceID := segments[1]

				switch resourceType {
				case "container":
					b.WriteString(fmt.Sprintf("  docker rm -f '%s' || true\n", resourceID))
				case "image":
					b.WriteString(fmt.Sprintf("  docker rmi -f '%s' || true\n", resourceID))
				case "volume":
					b.WriteString(fmt.Sprintf("  docker volume rm '%s' || true\n", resourceID))
				}
			}
			b.WriteString("else\n")
			b.WriteString("  echo -e \"${YELLOW}[SKIP]${NC} Docker not available\"\n")
			b.WriteString("fi\n\n")
			continue
		}

		// For filesystem-based cleaners, emit rm commands (files) and rm -rf (dirs).
		for _, entry := range result.Entries {
			// Escape single quotes in paths for shell safety.
			escaped := strings.ReplaceAll(entry.Path, "'", "'\\''")
			if entry.IsDir {
				b.WriteString(fmt.Sprintf("safe_rm_rf '%s'\n", escaped))
			} else {
				b.WriteString(fmt.Sprintf("safe_rm '%s'\n", escaped))
			}
		}
		b.WriteString("\n")
	}

	// Summary.
	b.WriteString("echo \"\"\n")
	b.WriteString("echo -e \"${GREEN}Done!${NC}\"\n")
	b.WriteString("echo \"  Files deleted: $DELETED\"\n")
	b.WriteString("echo \"  Files skipped: $SKIPPED\"\n")
	b.WriteString("echo \"  Errors: $ERRORS\"\n")

	if needsSudo {
		b.WriteString("echo \"\"\n")
		b.WriteString("echo -e \"${YELLOW}Tip:${NC} Re-run with sudo to clean system paths.\"\n")
	}

	if err := os.WriteFile(outputPath, []byte(b.String()), 0755); err != nil {
		return "", fmt.Errorf("scriptgen: write %s: %w", outputPath, err)
	}

	return outputPath, nil
}

// totalFiles sums the total number of files across all categories.
func totalFiles(results map[cleaner.Category]*cleaner.ScanResult) int {
	n := 0
	for _, r := range results {
		n += r.TotalFiles
	}
	return n
}

// totalBytes sums the total size in bytes across all categories.
func totalBytes(results map[cleaner.Category]*cleaner.ScanResult) int64 {
	var n int64
	for _, r := range results {
		n += r.TotalSize
	}
	return n
}
